name: DSMR-reader issue
description: Only for DSMR-reader specific stuff.
title: '?'
body:
  - type: dropdown
    id: language
    attributes:
      label: Communicatietaal / Language
      description: |
        - *🇳🇱 Voel je vooral vrij om in het Nederlands te communiceren, ondanks dat het project technisch Engelstalig is.* 
        - *🇬🇧 Unable to communicate in Dutch? Welcome anyway! Feel free to use English.*
      options:
        - '🇳🇱 Nederlandstalig'
        - '🇬🇧 English'
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Help yourself
      description: Most of the times you can help yourself by checking the guides or previous solutions.  Verify each one of these.
      options:
        - label: "I've checked [the how-to guides](https://dsmr-reader.readthedocs.io/nl/v5/how-to/index.html)"
          required: true
        - label: "I've checked previous [questions](https://github.com/dsmrreader/dsmr-reader/discussions)"
          required: true
        - label: "I've checked (recent) [previous issues](https://github.com/dsmrreader/dsmr-reader/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc) and their solutions"
          required: true
        - label: "I've checked the [logfiles](https://dsmr-reader.readthedocs.io/nl/v5/how-to/troubleshooting/logfiles.html) *(when applicable)*"
          required: true

  - type: markdown
    attributes:
      value: ----

  - type: dropdown
    id: inquiry
    attributes:
      label: Inquiry
      description: What do you need?
      options:
        - 'Help with installation or upgrade'
        - 'Report a bug'
        - 'Feature or idea'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 'Description'
      description: 'Your issue, suggestion or bug description'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ----
        *Please provide additional information below.*

  - type: input
    id: dsmrreader-version
    attributes:
      label: DSMR-reader version
      description: What version are you using? E.g. ``v5.10.2``.
      placeholder: vX.Y.Z
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: DSMR-reader platform
      description: How do you run DSMR-reader?
      options:
        - "Native (e.g. manual installation)"
        - "Docker (e.g. Xirixiz's DSMR-reader Docker)"
        - "Other (e.g. Home Assistant Plugin)"
    validations:
      required: true

  - type: textarea
    id: debug-info-dump
    attributes:
      label: 'Optional: Debug info dump (of DSMR-reader)'
      description: |
        When applicable, add a [dsmr_debuginfo dump](https://dsmr-reader.readthedocs.io/nl/v5/how-to/troubleshooting/debug-info-dump.html) below.
        This will be automatically formatted into code, so no need for backticks.
      render: shell-script

  - type: textarea
    id: telegram
    attributes:
      label: 'Optional: Smart meter telegram'
      description: |
        When applicable (e.g. on readings mismatch), add a [data telegram](https://dsmr-reader.readthedocs.io/nl/v5/explained/about.html#support) below.
      render: shell-script
